/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: 'var(--brand-primary)',
          accent: 'var(--brand-accent)',
        },
        sprout: {
          50:  '#f4f9f0',
          100: '#e6f2dc',
          200: '#cce5ba',
          300: '#a8d88f',
          400: '#7bc462',
          500: '#5aad42',
          600: '#489234',
          700: '#3a7829',
          800: '#2d5e1f',
          900: '#1f4215',
        },
        soil: {
          50:  '#faf6f1',
          100: '#f3ebe0',
          200: '#e8d9c5',
          300: '#d4c4a8',
          400: '#c4a87c',
          500: '#a68f5e',
          600: '#8a6f47',
          700: '#6b5640',
          800: '#4a3f32',
          900: '#332b22',
        },
        coin: {
          100: '#fdf4d4',
          400: '#f0c040',
          500: '#dba520',
          600: '#b8860b',
          700: '#96700a',
        },
        xp: {
          100: '#fdf4d4',
          400: '#f0c040',
          500: '#dba520',
          600: '#b8860b',
        },
        streak: {
          100: '#fdf0e4',
          400: '#e8a838',
          500: '#d4922a',
          600: '#b87a1f',
        },
        easy: {
          100: '#e6f2dc',
          500: '#5aad42',
          600: '#489234',
          700: '#3a7829',
        },
        medium: {
          100: '#fdf4e4',
          500: '#e8a838',
          600: '#d4922a',
          700: '#b87a1f',
        },
        hard: {
          100: '#fce8e4',
          500: '#d4604a',
          600: '#c04e38',
          700: '#a33f2c',
        },
        mood: {
          droopy: '#d4c88a',
          sad: '#a8a8a8',
        },
        danger: {
          50:  '#fdf2f2',
          200: '#f5c4c4',
          500: '#c94444',
          600: '#b33a3a',
        },
        /* Semantic aliases — map to soil palette */
        surface: {
          canvas: 'var(--surface-canvas)',
          card: 'var(--surface-card)',
          elevated: 'var(--surface-elevated)',
        },
        ink: {
          DEFAULT: 'var(--ink-default)',
          secondary: 'var(--ink-secondary)',
          muted: 'var(--ink-muted)',
        },
        line: {
          subtle: 'var(--line-subtle)',
          strong: 'var(--line-strong)',
        },
      },
      fontFamily: {
        sans: ['var(--font-body)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs:    ['var(--text-xs)', { lineHeight: '1.4' }],
        sm:    ['var(--text-sm)', { lineHeight: '1.5' }],
        base:  ['var(--text-base)', { lineHeight: '1.5' }],
        lg:    ['var(--text-lg)', { lineHeight: '1.35' }],
        xl:    ['var(--text-xl)', { lineHeight: '1.2' }],
        '2xl': ['var(--text-2xl)', { lineHeight: '1.15', letterSpacing: '-0.015em' }],
        display: ['var(--text-2xl)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        title:   ['var(--text-2xl)', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        heading: ['var(--text-lg)', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' }],
        body:    ['var(--text-sm)', { lineHeight: '1.5', fontWeight: '400' }],
        label:   ['0.6875rem', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.06em' }],
        caption: ['var(--text-xs)', { lineHeight: '1.4', fontWeight: '400' }],
        stat:    ['var(--text-2xl)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        kpi:     ['var(--text-2xl)', { lineHeight: '1', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      spacing: {
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '2rem',
        8: '2.5rem',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
        '4xl': '1.5rem',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        inner: 'inset 0 1px 3px rgba(74, 63, 50, 0.12)',
        card: 'var(--shadow-sm)',
        lift: 'var(--shadow-lg)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        breathe: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-3px)' },
        },
        sparkle: {
          '0%, 100%': { opacity: '0.2', transform: 'scale(0.8)' },
          '50%': { opacity: '1', transform: 'scale(1)' },
        },
      },
      animation: {
        breathe: 'breathe 3s ease-in-out infinite',
        'breathe-slow': 'breathe 5s ease-in-out infinite',
        sparkle: 'sparkle 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
