export const SHOP_ITEMS = [
  {
    id: 'star',
    name: 'Gold Star',
    price: 50,
    emoji: '⭐',
    category: 'badge',
    description: "You're a star!",
    slot: 'badge',
  },
  {
    id: 'sunglasses',
    name: 'Cool Shades',
    price: 75,
    emoji: '😎',
    category: 'face',
    description: 'Too cool for weeds.',
    slot: 'face',
  },
  {
    id: 'bowtie',
    name: 'Bow Tie',
    price: 80,
    emoji: '🎀',
    category: 'neck',
    description: 'Looking fancy!',
    slot: 'neck',
  },
  {
    id: 'partyhat',
    name: 'Party Hat',
    price: 100,
    emoji: '🎉',
    category: 'hat',
    description: 'Every day is a party!',
    slot: 'hat',
  },
  {
    id: 'floral',
    name: 'Flower Crown',
    price: 120,
    emoji: '🌸',
    category: 'hat',
    description: 'Bloom where you are planted.',
    slot: 'hat',
  },
  {
    id: 'crown',
    name: 'Royal Crown',
    price: 150,
    emoji: '👑',
    category: 'hat',
    description: 'Fit for plant royalty.',
    slot: 'hat',
  },
  {
    id: 'rainbow',
    name: 'Rainbow',
    price: 200,
    emoji: '🌈',
    category: 'background',
    description: 'Magical vibes only.',
    slot: 'background',
  },
]

export const TASK_REWARDS = {
  easy:   { health: 10, coins: 5  },
  medium: { health: 20, coins: 15 },
  hard:   { health: 35, coins: 30 },
}
